version: '3.8'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm run start:user

  store:
    build:
      context: .
      dockerfile: Dockerfile.store
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm run start:store
  
  match:
    build:
      context: .
      dockerfile: Dockerfile.match
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm run start:match

  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"

  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx:ro
    ports:
      - "80:80"
    depends_on:
      - user
      - store
      - match
