version: '3.8'

services:
  users-api:
    build: ./users-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
  proxy:
    image: nginx
      volumes:
        - ./proxy:/etc/nginx:ro           #En read-only 
      ports:
        - "80:80"
      depends_on:
        - users
        - another-microservice
