/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **creatures**
   * - Table in database
   */
  export namespace creatures {
    export type Table = 'creatures';
    export interface Selectable {
      /**
      * **creatures.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('creatures_id_seq'::regclass)`
      */
      id: number;
      /**
      * **creatures.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name: string | null;
      /**
      * **creatures.hp**
      * - `int4` in database
      * - Nullable, no default
      */
      hp: number | null;
      /**
      * **creatures.attack**
      * - `int4` in database
      * - Nullable, no default
      */
      attack: number | null;
      /**
      * **creatures.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type: string | null;
      /**
      * **creatures.price**
      * - `int4` in database
      * - Nullable, no default
      */
      price: number | null;
    }
    export interface JSONSelectable {
      /**
      * **creatures.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('creatures_id_seq'::regclass)`
      */
      id: number;
      /**
      * **creatures.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name: string | null;
      /**
      * **creatures.hp**
      * - `int4` in database
      * - Nullable, no default
      */
      hp: number | null;
      /**
      * **creatures.attack**
      * - `int4` in database
      * - Nullable, no default
      */
      attack: number | null;
      /**
      * **creatures.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type: string | null;
      /**
      * **creatures.price**
      * - `int4` in database
      * - Nullable, no default
      */
      price: number | null;
    }
    export interface Whereable {
      /**
      * **creatures.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('creatures_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **creatures.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **creatures.hp**
      * - `int4` in database
      * - Nullable, no default
      */
      hp?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **creatures.attack**
      * - `int4` in database
      * - Nullable, no default
      */
      attack?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **creatures.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **creatures.price**
      * - `int4` in database
      * - Nullable, no default
      */
      price?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **creatures.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('creatures_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **creatures.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **creatures.hp**
      * - `int4` in database
      * - Nullable, no default
      */
      hp?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **creatures.attack**
      * - `int4` in database
      * - Nullable, no default
      */
      attack?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **creatures.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **creatures.price**
      * - `int4` in database
      * - Nullable, no default
      */
      price?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **creatures.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('creatures_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **creatures.name**
      * - `varchar` in database
      * - Nullable, no default
      */
      name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **creatures.hp**
      * - `int4` in database
      * - Nullable, no default
      */
      hp?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **creatures.attack**
      * - `int4` in database
      * - Nullable, no default
      */
      attack?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **creatures.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **creatures.price**
      * - `int4` in database
      * - Nullable, no default
      */
      price?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'creatures_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **matches**
   * - Table in database
   */
  export namespace matches {
    export type Table = 'matches';
    export interface Selectable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matches.player1**
      * - `int4` in database
      * - Nullable, no default
      */
      player1: number | null;
      /**
      * **matches.player2**
      * - `int4` in database
      * - Nullable, no default
      */
      player2: number | null;
      /**
      * **matches.round1**
      * - `int4` in database
      * - Nullable, no default
      */
      round1: number | null;
      /**
      * **matches.round2**
      * - `int4` in database
      * - Nullable, no default
      */
      round2: number | null;
      /**
      * **matches.round3**
      * - `int4` in database
      * - Nullable, no default
      */
      round3: number | null;
      /**
      * **matches.round4**
      * - `int4` in database
      * - Nullable, no default
      */
      round4: number | null;
      /**
      * **matches.round5**
      * - `int4` in database
      * - Nullable, no default
      */
      round5: number | null;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner: number | null;
    }
    export interface JSONSelectable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id: number;
      /**
      * **matches.player1**
      * - `int4` in database
      * - Nullable, no default
      */
      player1: number | null;
      /**
      * **matches.player2**
      * - `int4` in database
      * - Nullable, no default
      */
      player2: number | null;
      /**
      * **matches.round1**
      * - `int4` in database
      * - Nullable, no default
      */
      round1: number | null;
      /**
      * **matches.round2**
      * - `int4` in database
      * - Nullable, no default
      */
      round2: number | null;
      /**
      * **matches.round3**
      * - `int4` in database
      * - Nullable, no default
      */
      round3: number | null;
      /**
      * **matches.round4**
      * - `int4` in database
      * - Nullable, no default
      */
      round4: number | null;
      /**
      * **matches.round5**
      * - `int4` in database
      * - Nullable, no default
      */
      round5: number | null;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner: number | null;
    }
    export interface Whereable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.player1**
      * - `int4` in database
      * - Nullable, no default
      */
      player1?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.player2**
      * - `int4` in database
      * - Nullable, no default
      */
      player2?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.round1**
      * - `int4` in database
      * - Nullable, no default
      */
      round1?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.round2**
      * - `int4` in database
      * - Nullable, no default
      */
      round2?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.round3**
      * - `int4` in database
      * - Nullable, no default
      */
      round3?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.round4**
      * - `int4` in database
      * - Nullable, no default
      */
      round4?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.round5**
      * - `int4` in database
      * - Nullable, no default
      */
      round5?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **matches.player1**
      * - `int4` in database
      * - Nullable, no default
      */
      player1?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.player2**
      * - `int4` in database
      * - Nullable, no default
      */
      player2?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.round1**
      * - `int4` in database
      * - Nullable, no default
      */
      round1?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.round2**
      * - `int4` in database
      * - Nullable, no default
      */
      round2?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.round3**
      * - `int4` in database
      * - Nullable, no default
      */
      round3?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.round4**
      * - `int4` in database
      * - Nullable, no default
      */
      round4?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.round5**
      * - `int4` in database
      * - Nullable, no default
      */
      round5?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **matches.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('matches_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.player1**
      * - `int4` in database
      * - Nullable, no default
      */
      player1?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.player2**
      * - `int4` in database
      * - Nullable, no default
      */
      player2?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.round1**
      * - `int4` in database
      * - Nullable, no default
      */
      round1?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.round2**
      * - `int4` in database
      * - Nullable, no default
      */
      round2?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.round3**
      * - `int4` in database
      * - Nullable, no default
      */
      round3?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.round4**
      * - `int4` in database
      * - Nullable, no default
      */
      round4?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.round5**
      * - `int4` in database
      * - Nullable, no default
      */
      round5?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **matches.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'matches_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **players**
   * - Table in database
   */
  export namespace players {
    export type Table = 'players';
    export interface Selectable {
      /**
      * **players.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number;
      /**
      * **players.creatures**
      * - `varchar` in database
      * - Nullable, no default
      */
      creatures: string | null;
      /**
      * **players.credits**
      * - `int4` in database
      * - Nullable, no default
      */
      credits: number | null;
      /**
      * **players.wins**
      * - `int4` in database
      * - Nullable, no default
      */
      wins: number | null;
      /**
      * **players.loss**
      * - `int4` in database
      * - Nullable, no default
      */
      loss: number | null;
      /**
      * **players.score**
      * - `int4` in database
      * - Nullable, no default
      */
      score: number | null;
      /**
      * **players.badges**
      * - `varchar` in database
      * - Nullable, no default
      */
      badges: string | null;
    }
    export interface JSONSelectable {
      /**
      * **players.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number;
      /**
      * **players.creatures**
      * - `varchar` in database
      * - Nullable, no default
      */
      creatures: string | null;
      /**
      * **players.credits**
      * - `int4` in database
      * - Nullable, no default
      */
      credits: number | null;
      /**
      * **players.wins**
      * - `int4` in database
      * - Nullable, no default
      */
      wins: number | null;
      /**
      * **players.loss**
      * - `int4` in database
      * - Nullable, no default
      */
      loss: number | null;
      /**
      * **players.score**
      * - `int4` in database
      * - Nullable, no default
      */
      score: number | null;
      /**
      * **players.badges**
      * - `varchar` in database
      * - Nullable, no default
      */
      badges: string | null;
    }
    export interface Whereable {
      /**
      * **players.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **players.creatures**
      * - `varchar` in database
      * - Nullable, no default
      */
      creatures?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **players.credits**
      * - `int4` in database
      * - Nullable, no default
      */
      credits?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **players.wins**
      * - `int4` in database
      * - Nullable, no default
      */
      wins?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **players.loss**
      * - `int4` in database
      * - Nullable, no default
      */
      loss?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **players.score**
      * - `int4` in database
      * - Nullable, no default
      */
      score?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **players.badges**
      * - `varchar` in database
      * - Nullable, no default
      */
      badges?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **players.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **players.creatures**
      * - `varchar` in database
      * - Nullable, no default
      */
      creatures?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **players.credits**
      * - `int4` in database
      * - Nullable, no default
      */
      credits?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **players.wins**
      * - `int4` in database
      * - Nullable, no default
      */
      wins?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **players.loss**
      * - `int4` in database
      * - Nullable, no default
      */
      loss?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **players.score**
      * - `int4` in database
      * - Nullable, no default
      */
      score?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **players.badges**
      * - `varchar` in database
      * - Nullable, no default
      */
      badges?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **players.id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **players.creatures**
      * - `varchar` in database
      * - Nullable, no default
      */
      creatures?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **players.credits**
      * - `int4` in database
      * - Nullable, no default
      */
      credits?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **players.wins**
      * - `int4` in database
      * - Nullable, no default
      */
      wins?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **players.loss**
      * - `int4` in database
      * - Nullable, no default
      */
      loss?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **players.score**
      * - `int4` in database
      * - Nullable, no default
      */
      score?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **players.badges**
      * - `varchar` in database
      * - Nullable, no default
      */
      badges?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'players_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **rounds**
   * - Table in database
   */
  export namespace rounds {
    export type Table = 'rounds';
    export interface Selectable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id: number;
      /**
      * **rounds.creatureplayer1**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer1: number | null;
      /**
      * **rounds.creatureplayer2**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer2: number | null;
      /**
      * **rounds.status**
      * - `varchar` in database
      * - Nullable, no default
      */
      status: string | null;
      /**
      * **rounds.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner: number | null;
    }
    export interface JSONSelectable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id: number;
      /**
      * **rounds.creatureplayer1**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer1: number | null;
      /**
      * **rounds.creatureplayer2**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer2: number | null;
      /**
      * **rounds.status**
      * - `varchar` in database
      * - Nullable, no default
      */
      status: string | null;
      /**
      * **rounds.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner: number | null;
    }
    export interface Whereable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.creatureplayer1**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer1?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.creatureplayer2**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer2?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.status**
      * - `varchar` in database
      * - Nullable, no default
      */
      status?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **rounds.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.creatureplayer1**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer1?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.creatureplayer2**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer2?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.status**
      * - `varchar` in database
      * - Nullable, no default
      */
      status?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **rounds.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **rounds.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('rounds_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.creatureplayer1**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer1?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.creatureplayer2**
      * - `int4` in database
      * - Nullable, no default
      */
      creatureplayer2?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.status**
      * - `varchar` in database
      * - Nullable, no default
      */
      status?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **rounds.winner**
      * - `int4` in database
      * - Nullable, no default
      */
      winner?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'rounds_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **users**
   * - Table in database
   */
  export namespace users {
    export type Table = 'users';
    export interface Selectable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id: number;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username: string | null;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password: string | null;
      /**
      * **users.email**
      * - `varchar` in database
      * - Nullable, no default
      */
      email: string | null;
    }
    export interface JSONSelectable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id: number;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username: string | null;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password: string | null;
      /**
      * **users.email**
      * - `varchar` in database
      * - Nullable, no default
      */
      email: string | null;
    }
    export interface Whereable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.email**
      * - `varchar` in database
      * - Nullable, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **users.email**
      * - `varchar` in database
      * - Nullable, no default
      */
      email?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **users.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('users_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.username**
      * - `varchar` in database
      * - Nullable, no default
      */
      username?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.password**
      * - `varchar` in database
      * - Nullable, no default
      */
      password?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **users.email**
      * - `varchar` in database
      * - Nullable, no default
      */
      email?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'users_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = creatures.Table | matches.Table | players.Table | rounds.Table | users.Table;
    export type Selectable = creatures.Selectable | matches.Selectable | players.Selectable | rounds.Selectable | users.Selectable;
    export type JSONSelectable = creatures.JSONSelectable | matches.JSONSelectable | players.JSONSelectable | rounds.JSONSelectable | users.JSONSelectable;
    export type Whereable = creatures.Whereable | matches.Whereable | players.Whereable | rounds.Whereable | users.Whereable;
    export type Insertable = creatures.Insertable | matches.Insertable | players.Insertable | rounds.Insertable | users.Insertable;
    export type Updatable = creatures.Updatable | matches.Updatable | players.Updatable | rounds.Updatable | users.Updatable;
    export type UniqueIndex = creatures.UniqueIndex | matches.UniqueIndex | players.UniqueIndex | rounds.UniqueIndex | users.UniqueIndex;
    export type Column = creatures.Column | matches.Column | players.Column | rounds.Column | users.Column;
  
    export type AllBaseTables = [creatures.Table, matches.Table, players.Table, rounds.Table, users.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [creatures.Table, matches.Table, players.Table, rounds.Table, users.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "creatures": creatures.Selectable;
    "matches": matches.Selectable;
    "players": players.Selectable;
    "rounds": rounds.Selectable;
    "users": users.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "creatures": creatures.JSONSelectable;
    "matches": matches.JSONSelectable;
    "players": players.JSONSelectable;
    "rounds": rounds.JSONSelectable;
    "users": users.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "creatures": creatures.Whereable;
    "matches": matches.Whereable;
    "players": players.Whereable;
    "rounds": rounds.Whereable;
    "users": users.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "creatures": creatures.Insertable;
    "matches": matches.Insertable;
    "players": players.Insertable;
    "rounds": rounds.Insertable;
    "users": users.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "creatures": creatures.Updatable;
    "matches": matches.Updatable;
    "players": players.Updatable;
    "rounds": rounds.Updatable;
    "users": users.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "creatures": creatures.UniqueIndex;
    "matches": matches.UniqueIndex;
    "players": players.UniqueIndex;
    "rounds": rounds.UniqueIndex;
    "users": users.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "creatures": creatures.Column;
    "matches": matches.Column;
    "players": players.Column;
    "rounds": rounds.Column;
    "users": users.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "creatures": creatures.SQL;
    "matches": matches.SQL;
    "players": players.SQL;
    "rounds": rounds.SQL;
    "users": users.SQL;
  }[T];

}
